### ISSUE TITLE
halo2wrong optimization: ECDSA signature verification

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#14]
Look into how this can be optimized.

Batch verification resources:
- https://0xparc.org/blog/batch-ecdsa
- https://github.com/privacy-scaling-explorations/halo2wrong/pull/22
- https://0xparc.org/blog/zk-ecdsa-2

**Comment by kullervo-wanona** [comment]
Could be interested in this with some support from other team members.
