### ISSUE TITLE
Investigate Verkle trees

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#22]
- https://notes.ethereum.org/@dankrad/kzg_commitments_in_proofs
- https://notes.ethereum.org/@vbuterin/proto_danksharding_faq#Moderate-approach-works-with-any-ZK-SNARK

**Comment by kullervo-wanona** [comment]
I have already investigated and have written about Verkle Trees in the commitment schemes work. Is there something else you wish to investigate @Brechtpd ?

**Comment by Brechtpd** [comment]
I think we still need to investigate a bit (or at least understand) how to efficiently implement this in a circuit. For the verkle tree we'll have to work on KZG commitments of a different curve (the verkle trees will be over BLS12-381) which complicates things. That's where the link in the first post comes in, it describes a method to work with commitments over a different curve in a proof efficiently.

**Comment by kullervo-wanona** [comment]
Ok, you mean if Verkle trees are used in the EVM computation, how would we create a circuit efficiently to include in our proof? They are implemented using the regular EVM opcodes. We just need to prove individual opcode calls. You are suggesting that this could be costly and whether you can improve it?

**Comment by Brechtpd** [comment]
> Ok, you mean if Verkle trees are used in the EVM computation, how would we create a circuit efficiently to include in our proof? 

Yep, I'm talking mostly for the state tree update which are not done directly in the EVM circuit. In the EVM circuit we just see things like SLOAD and SSTORE that can load/store data from the state tree. The actual work necessary for these are handled by a different circuit (currently a Merkle tree is used and so there's a separate circuit to do the reads/writes for those). With Verkle trees we'll have to create a similar circuit that does all the state reading/writing verification that is then consumed by the EVM circuit. So how we do the Verkle tree reads/writes is fully up to the circuit and we can do whatever we can to make it as efficient as possible (not limited by EVM opcodes). State reads are of course done quite often in smart contracts and the gas cost for these isn't always high so it's important we can do these Verkle tree operations pretty efficiently.

**Comment by mratsim** [comment]
Note that the current design of Verkle trees will not use KZG but IPA over Banderwagon (i.e. Bandersnatch, a 255-bit Twisted Edwards curve + Decaf/Ristretto):
- https://hackmd.io/@6iQDuIePQjyYBqDChYw_jg/B1rUOM9Zq#IPA
- https://hackmd.io/wliPP_RMT4emsucVuCqfHA?view
