### ISSUE TITLE
Investigate Caulk

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#23]
- https://www.youtube.com/watch?v=mwimLQ3uaHw
- https://twitter.com/arantxazapico/status/1545318810558799873?s=21&t=Thc31573e1IoOwo3GVzhxA
- Flookup: https://hackmd.io/_eKVj_E9RPaVxNLbavNLAw

**Comment by mabbamOG** [comment]
WIP: https://mabbamog.notion.site/Caulk-Vector-Commitments-Lookup-Tables-b7dacf331cd345da8d59d7cf6dcae875
