### ISSUE TITLE
Investigate HyperPlonk

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#27]
- https://eprint.iacr.org/2022/1355
- https://www.espressosys.com/blog/hyperplonk-a-zk-proof-system-for-zkevms
- zkStudyClub: HyperPlonk - https://www.youtube.com/watch?v=J51Ajp6zzkI

**Comment by ChengYueJia** [comment]
Hi，here is a Hyperplonk share from Benedikt.
https://www.youtube.com/watch?v=mZEXgoQL6xk

**Comment by smtmfft** [comment]
Thanks @ChengYueJia for sharing. Looks like you have experiences on ZK?? We are hiring ZK engineers now, if you have interesting, please contract with us (my email: smtm@taiko.xyz). Thanks!

**Comment by ChengYueJia** [comment]
> Thanks @ChengYueJia for sharing. Looks like you have experiences on ZK?? We are hiring ZK engineers now, if you have interesting, please contract with us (my email: [smtm@taiko.xyz](mailto:smtm@taiko.xyz)). Thanks!

Thank's for your invitation. I've seed email.
