### ISSUE TITLE
Prover optimization: Don't run the witness generation twice

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#7]
Currently the witness generation is always run twice because of the halo2 layouter. Many of the circuits don't depend on the layouter so this isn't necessary. So the solution here may be to just make the system a little bit smarter so halo2 knows when it needs to run it twice or not.

**Comment by smtmfft** [comment]
Yes, I have seen this strange behavior. Is there an example of a circuit which depends on the layouter?
