### ISSUE TITLE
Prover optimization: memory reduction

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/zkevm-circuits#77]
Performance is a bit worse, but this can save a lot of memory: https://github.com/scroll-tech/halo2/pull/28
Original idea from here: https://github.com/zcash/halo2/issues/427

**Comment by einar-taiko** [comment]
It looks promising, but AFAICT, it's still WIP:  Clippy complains about a  `if false && condition` statement, so I would suggest we wait until it is finalized.

**Comment by Brechtpd** [comment]
Diff is pretty small, and this will be very important for running the super circuit/root circuit, so would like to get this in sooner than later. Please try it out and see if it works after the FFT, if there aren't any significant issues would like to start using is as soon as possible.
